### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by vcvishal** [overshiki/unet-pytorch#1]
Traceback (most recent call last):
  File "isbi2012.py", line 1, in <module>
    from model import *
  File "C:\Users\vcvis\Desktop\test\unet-pytorch-master\model.py", line 88, in <module>
    from utils import loader, train
  File "C:\Users\vcvis\Desktop\test\unet-pytorch-master\utils.py", line 5, in <module>
    from BASIC_LIST.basic import groupby
ModuleNotFoundError: No module named 'BASIC_LIST'

**Comment by teymour-aldridge** [comment]
The variable also appears to be overwritten when two or three lines down in the program it is redefined as a function.

**Comment by overshiki** [comment]
sorry for late response. It is happy to see this package is helpful to you.
The groupby function originally located in a subdir called BASIC_LIST which I have removed. The function now just lie in utils.py file two or three lines down and I just forget to remove the 'import' claim.

It may be late for you guys, but I now fix this bug anyway.
